'use strict';

/*
 * Bakes payload/translation.js into src/payload.generated.js as a base64 string
 * so the packaged executable is fully self-contained.
 *
 * payload/translation.js contains ONLY the injected translation code -- none of
 * TETR.IO's own source. The patcher appends it to the stock preload.js that it
 * reads from the user's own installed app.asar at patch time.
 *
 * Run automatically by `npm run patch` / `npm run build`, and by CI before pkg.
 */

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const src = path.join(root, 'payload', 'translation.js');
const dest = path.join(root, 'src', 'payload.generated.js');
const pkg = require(path.join(root, 'package.json'));

// Unique boundary line written between the stock preload and the injection.
// Also used to detect / strip a previous patch. Must not occur in translation.js.
const SENTINEL = 'TETRIO-ES-PATCH:INJECT-BOUNDARY';
const banner =
  `// ===== ${SENTINEL} v${pkg.version} =====\n` +
  `// Todo lo que está por encima de esta línea es el preload.js propio de TETR.IO, sin tocar.\n` +
  `// Todo lo que está por debajo es la traducción al español de la comunidad (tetrio-es-patcher).\n`;

if (!fs.existsSync(src)) {
  console.error(`[gen-payload] missing ${src}`);
  process.exit(1);
}

const translation = fs.readFileSync(src, 'utf8');

if (translation.includes(SENTINEL)) {
  console.error(
    `[gen-payload] payload/translation.js contains the reserved sentinel ` +
      `"${SENTINEL}". Remove it -- it is used as the patch boundary marker.`
  );
  process.exit(1);
}
if (/window\.IS_ELECTRON|invoke\(['"]get-systeminfo/.test(translation)) {
  console.error(
    `[gen-payload] payload/translation.js looks like it still contains TETR.IO's ` +
      `stock preload stub. It must hold ONLY the injected translation code.`
  );
  process.exit(1);
}

const body = `// AUTO-GENERATED by scripts/gen-payload.js -- do not edit, not committed.
'use strict';
module.exports = {
  version: ${JSON.stringify(pkg.version)},
  sentinel: ${JSON.stringify(SENTINEL)},
  banner: ${JSON.stringify(banner)},
  translationB64: ${JSON.stringify(Buffer.from(translation, 'utf8').toString('base64'))}
};
`;

fs.writeFileSync(dest, body);
console.log(
  `[gen-payload] embedded payload/translation.js (${Buffer.byteLength(translation)} bytes) ` +
    `-> src/payload.generated.js`
);
